config/routes.rb
Rails.application.routes.draw do
  resources :people
  resources :faculties
  resources :theses

  root 'theses#index'

end

app/models/faculty.rb
class Faculty < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_many :theses

  validates :username, presence: true, uniqueness:true
  validates :firstname, presence: true
  validates :surname, presence: true
end

app/models/thesis.rb
class Thesis < ActiveRecord::Base
  belongs_to :faculty

  validates :title, presence: true
  validates :abstract, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  before_action :set_faculty, only: [:show, :edit, :update, :destroy]

  # GET /faculties
  # GET /faculties.json
  def index
    @faculties = Faculty.all
  end

  # GET /faculties/1
  # GET /faculties/1.json
  def show
  end

  # GET /faculties/new
  def new
    @faculty = Faculty.new
  end

  # GET /faculties/1/edit
  def edit
  end

  # POST /faculties
  # POST /faculties.json
  def create
    @faculty = Faculty.new(faculty_params)

    respond_to do |format|
      if @faculty.save
        format.html { redirect_to @faculty, notice: 'Faculty was successfully created.' }
        format.json { render :show, status: :created, location: @faculty }
      else
        format.html { render :new }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faculties/1
  # PATCH/PUT /faculties/1.json
  def update
    respond_to do |format|
      if @faculty.update(faculty_params)
        format.html { redirect_to @faculty, notice: 'Faculty was successfully updated.' }
        format.json { render :show, status: :ok, location: @faculty }
      else
        format.html { render :edit }
        format.json { render json: @faculty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faculties/1
  # DELETE /faculties/1.json
  def destroy
    @faculty.destroy
    respond_to do |format|
      format.html { redirect_to faculties_url, notice: 'Faculty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faculty
      @faculty = Faculty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faculty_params
      params.require(:faculty).permit(:name, :code)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:username, :firstname, :surname)
    end
end

app/controllers/theses_controller.rb
class ThesesController < ApplicationController
  before_action :set_thesis, only: [:show, :edit, :update, :destroy]

  # GET /theses
  # GET /theses.json
  def index
    @theses = Thesis.all
  end

  # GET /theses/1
  # GET /theses/1.json
  def show
  end

  # GET /theses/new
  def new
    @thesis = Thesis.new
  end

  # GET /theses/1/edit
  def edit
  end

  # POST /theses
  # POST /theses.json
  def create
    @thesis = Thesis.new(thesis_params)

    respond_to do |format|
      if @thesis.save
        format.html { redirect_to @thesis, notice: 'Thesis was successfully created.' }
        format.json { render :show, status: :created, location: @thesis }
      else
        format.html { render :new }
        format.json { render json: @thesis.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /theses/1
  # PATCH/PUT /theses/1.json
  def update
    respond_to do |format|
      if @thesis.update(thesis_params)
        format.html { redirect_to @thesis, notice: 'Thesis was successfully updated.' }
        format.json { render :show, status: :ok, location: @thesis }
      else
        format.html { render :edit }
        format.json { render json: @thesis.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /theses/1
  # DELETE /theses/1.json
  def destroy
    @thesis.destroy
    respond_to do |format|
      format.html { redirect_to theses_url, notice: 'Thesis was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thesis
      @thesis = Thesis.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def thesis_params
      params.require(:thesis).permit(:title, :abstract, :defended, :faculty_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/theses_helper.rb
module ThesesHelper
end

app/views/faculties/_form.html.erb
<%= form_for(@faculty) do |f| %>
  <% if @faculty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@faculty.errors.count, "error") %> prohibited this faculty from being saved:</h2>

      <ul>
      <% @faculty.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.number_field :code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/faculties/edit.html.erb
<h1>Editing Faculty</h1>

<%= render 'form' %>

<%= link_to 'Show', @faculty %> |
<%= link_to 'Back', faculties_path %>

app/views/faculties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Faculties</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @faculties.each do |faculty| %>
      <tr>
        <td><%= faculty.name %></td>
        <td><%= faculty.code %></td>
        <td><%= link_to 'Show', faculty %></td>
        <td><%= link_to 'Edit', edit_faculty_path(faculty) %></td>
        <td><%= link_to 'Destroy', faculty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Faculty', new_faculty_path %>

app/views/faculties/new.html.erb
<h1>New Faculty</h1>

<%= render 'form' %>

<%= link_to 'Back', faculties_path %>

app/views/faculties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @faculty.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @faculty.code %>
</p>

<%= link_to 'Edit', edit_faculty_path(@faculty) %> |
<%= link_to 'Back', faculties_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Theses</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </div>
  <div class="field">
    <%= f.label :surname %><br>
    <%= f.text_field :surname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing People</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Firstname</th>
      <th>Surname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.username %></td>
        <td><%= person.firstname %></td>
        <td><%= person.surname %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @person.username %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @person.firstname %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @person.surname %>
</p>

<% everyThesis = @person.theses.all %>
<% if everyThesis.size != 0 %>
  <p>
    <strong>Theses:</strong>
    <table>
      <tr>
        <td width=10% ><strong>Title</strong></td>
        <td width=20% ><strong>Abstract</strong></td>
        <td width=10% ><strong>Defended</strong></td>
      </tr>

      <% everyThesis.each do |thesis| %>
        <tr>
          <td width=10% ><%= link_to thesis.title, thesis  %></td>
          <td width=20% ><%= thesis.abstract %></td>
          <td width=10% ><%= thesis.defended %></td>
        </tr>
      <% end %>
    </table>
  </p>
<% end %>  

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/theses/_form.html.erb
<%= form_for(@thesis) do |f| %>
  <% if @thesis.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thesis.errors.count, "error") %> prohibited this thesis from being saved:</h2>

      <ul>
      <% @thesis.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :abstract %><br>
    <%= f.text_area :abstract %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.select :person_id, Person.all.collect { |f| [f.username, f.id] }, include_blank: true %>
  </div>
  <div class="field">
    <%= f.label :defended %><br>
    <%= f.date_select :defended %>
  </div>
  <div class="field">
    <%= f.label :faculty %><br>
    <%= f.select :faculty_id, Faculty.all.collect { |f| [f.name, f.id] }, include_blank: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/theses/edit.html.erb
<h1>Editing Thesis</h1>

<%= render 'form' %>

<%= link_to 'Show', @thesis %> |
<%= link_to 'Back', theses_path %>

app/views/theses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Theses</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Abstract</th>
      <th>Defended</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @theses.each do |thesis| %>
      <tr>
        <td><%= thesis.title %></td>
        <td><%= thesis.abstract %></td>
        <td><%= thesis.defended %></td>
        <td><%= link_to 'Show', thesis %></td>
        <td><%= link_to 'Edit', edit_thesis_path(thesis) %></td>
        <td><%= link_to 'Destroy', thesis, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Thesis', new_thesis_path %>

app/views/theses/new.html.erb
<h1>New Thesis</h1>

<%= render 'form' %>

<%= link_to 'Back', theses_path %>

app/views/theses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @thesis.title %>
</p>

<p>
  <strong>Abstract:</strong>
  <%= @thesis.abstract %>
</p>

<p>
  <strong>Author:</strong>
  <%= @thesis.person.try!(:username) %>
</p>

<p>
  <strong>Defended:</strong>
  <%= @thesis.defended %>
</p>

<p>
  <strong>Faculty:</strong>
  <%= @thesis.faculty.try!(:name) %>
</p>

<%= link_to 'Edit', edit_thesis_path(@thesis) %> |
<%= link_to 'Back', theses_path %>